export const CATEGORIES_ACTION_TYPE = {
  FETCH_CATEGOIRES_START: "category/FETCH_CATEGOIRES_START",
  FETCH_CATEGOIRES_SUCCESS: "category/FETCH_CATEGOIRES_SUCCESS",
  FETCH_CATEGOIRES_FAILED: "category/FETCH_CATEGOIRES_FAILED",
}